### ISSUE TITLE
Source code ?

### ISSUE THREAD

**Issue by koko-ng** [Seeed-Studio/Arduino_IDE_for_RePhone#1]
I just received my rephone, thanks it seems to be cool ! But where is the source code ? I am on linux so I can't use it now 😢.

**Comment by WayenWeng** [comment]
Hi, you can make reference to this example: 
https://github.com/Seeed-Studio/Lua_for_RePhone

**Comment by koko-ng** [comment]
I tried but it's very hard to use this with arduino ide, and I don't want to code in Lua !  You are lying about the product, you sell it as an "open-source" phone and everything, even the firmware, is closed source !

**Comment by SebiTimeWaster** [comment]
Well you are right, the modified Arduino IDE can only run under windows, but that doesn't necessary means they lied about Open Source capabilities. 
As i remember (correct me if i'm wrong) they never specified which parts of RePhone are Open Source. 
From what i tested so far i can tell you that (at least with the Arduino IDE) you can completely control all the parts of RePhone, from the display over the sensors to all the telephone functions directly from the main processor (which is awesome). That does not mean that the Open Source label is justified, especially if you consider the missing source code ~~for the pre-installed operating system~~ (strike that, i think here is the source code for that, although the documentation is more than thin and i didn't open the code myself: https://github.com/WayenWeng/RePhone_Create_Kit_Source_Code) or the hardware itself, but at least you can do everything you imagined with the hardware modules.

About the bootloader (I assume that is what you mean with "firmware"): I doubt that the bootloader will ever be Open Source, the bootloader is part of the CPU they are using and as such under the license of the manufacturer of the CPU. (The bootloader can be found here https://github.com/WayenWeng/RePhone_SDK_Bin_Update and is, as expected, just the closed source binary blobs.)

About that Linux thing, i suggest trying out wine (https://en.wikipedia.org/wiki/Wine_(software)) which is Open Source and should be more than capable of running the modified Arduino IDE.

What i would like to see is an official API documentation, atm one can only see from the example files what is possible.

**Comment by jamieisboss** [comment]
The arduino IDE is licensed GPL so if it's been modified, the entire source code should be available, ideally with a changelog and inline comments explaining what was changed and why. [Sections 2 and 3, specifically this](https://github.com/arduino/Arduino/blob/master/license.txt#L151)

So that any changes can be integrated into the main branch again if that's what people want, or so that say, a linux user would know what IDE changes hey would need to make to continue the development. This isn't even a fork of the main project and the license file has been remove do it's not only not open source, it's breaking the terms of the GPL for the  open source software they've taken and not credited the authors for. Yeah we all know who they are, but that;s not the point of contract law is it?

And suggesting the deliberately open source Arduino IDE should be run under wine on a deliberately open source Linux OS because there's some windows code that if you need wine to run, you don't want and probably need in Linux is so ridiculous as to be insulting to the people who gave their time writing all that code in the first place.

The version of the IDE they've taken (judging by the still present but not kept up to date revisions.txt) even has the capability and intent to have new hardware and libraries added to it without doing exactly this, keep the IDE as it is and then you can put whatever extra code you need in your board management. Then everyone would have the new features from the new ide versions (and the bugfixes)

**Comment by WayenWeng** [comment]
Hi,
These are some changes in the Arduino_IDE_for_RePhone.
0. Change the name from "arduino.exe" to " Arduino_IDE_for_RePhone.exe ", and delete the " arduino_debug.exe ".
1. Delete the library file in path ..\arduino\libraries.
2. Add the RePhone driver files to the path ..\arduino\drivers.
3. Add the RePhone firmware update tool to the path ..\arduino\hardware\tools.
4. Add the RePhone development files to the path ..\arduino\hardware\arduino.
5. Add the RePhone example codes to the path ..\arduino\workspace.
And these is not any changes in IDE environment.
Thanks.

**Comment by jamieisboss** [comment]
@WayenWeng Hi, thank you for explaining because it's not really clear from the readme file that the exe hasnt changed, for that reason and because until now there wasn't a list of changes you weren't  giving any Mac or Linux users the chance to replicate these changes and use the rephone modules (I have five kits sitting unused on a shelf, partly because all my machines run Ubuntu). 
- [There's information here on the arduino github wiki about how to package this information so anyone an add it to a normal install](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification). 
- [And Here in the Wiki about making that available through the board manager interface](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.6.x-package_index.json-format-specification)  Also I noticed that I've got seeeduino boards in my IDE because I've added them through the board manager so also I'd suggest that maybe you could speak with whoever is in charge of  seeeduino as they [have the board manager entry here](https://raw.githubusercontent.com/Seeed-Studio/Seeeduino-Boards/master/package_seeeduino_index.json) which lets me install the required files directly through the IDE, so should be able to help.
- [For Libraries the specification information is here in the wiki](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification)
- [And the information about how to get your Libraries into the library manager](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)

Doing this will allow everyone fair (and easier) access to the board and library code required and if anything, should help more people to use your product as this is the method that Arduino.cc are saing should be used.

Thank you for replying with the information you have, it shows that you are not trying to be unfair to anyone, I will say though, redistributing the Arduino environment without the license file is still a violation of the license and (while this wont really happen as I think you will not have to redistribute this at all if you do as Arduino.cc suggest anyway) could get you in trouble, I say this not as a threat but to help make sure you are aware that there were license terms you agreed to and then broke, so that you can be informed for the future. 

I appreciate the work you've done in bringing an innovative product to the market and respect the time and effort that must have taken, as well as your quick response here.  

I hope you see my taking time to find all of the information required and bring it together for you as well as my explanation of the license as a gesture of that respect which I trust you will continue to earn by updating the work you have done to be usable by everyone in the community.

Best Regards

Jamie

**Comment by xiongyihui** [comment]
Hi @jamieisboss 

Thank you for your efforts to find all the information.

Sorry, we forgot to upload a license file to describe the license of each part. We will add it later, and we will try to get the RePhone SDK supported by the board manager. At the moment, you can try [robarago's ArduinoGNULinux4RePhone](https://github.com/robarago/ArduinoGNULinux4RePhone) on Ubuntu. 

Do you mean it's a violation of the GPL license if we distribute close source binaries together with unmodified GPL binaries?

Thanks,
Yihui Xiong

**Comment by jamieisboss** [comment]
I'm not a lawyer so i cant give legal advice but [this section](https://github.com/arduino/Arduino/blob/master/license.txt#L92) reads :
1. You may copy and distribute verbatim copies of the Program's
   source code as you receive it, in any medium, provided that you
   conspicuously and appropriately publish on each copy an appropriate
   copyright notice and disclaimer of warranty; **keep** intact **all the
   notices that refer to this License** and to the absence of any warranty;
   **and give any other recipients of the Program a copy of this License**
   along with the Program.

I bolded the bits that lead me to think you cant distribute the unmodified GPL binaries without including the GPL license. Which i believe is the only real issue you have.

**I'll say again that i not a lawyer and i cannot give legal advice, if you wish to clarify the matter, a lawyer or the licensor should be consulted** (by this i mean: ask Arduino.cc, and they'll probably just tell you what is and is not ok, I understand they're very helpful) 

However, to finish my thinking. The reason I think you would not have an issue is that you would not need to distribute the IDE, only your own code, and if you're not distributing the IDE you don't have to include the GPL license with it, so the GPL or any GPL licensed binaries are not anywhere in the distributed software.

Generally though,  I think you would have to look at[ dual lcensing](http://oss-watch.ac.uk/resources/duallicence2) though i dont know if you'd need that here

**Comment by xiongyihui** [comment]
The license file is added. Sorry for our negligence. Thank you very much.

**Comment by xiongyihui** [comment]
@jamieisboss 
Just add experiential rephone sdk for board manager - https://github.com/Seeed-Studio/Seeeduino-Boards/raw/master/package_seeed_rephone_index.json

Tested with Arduino IDE 1.6.4, while v1.6.7 doesn't work

**Comment by jamieisboss** [comment]
Thank you, I have closed the other issue but can't close this one as i didn't open it, it seems to be resolved to me as you have dealt with the license issue, and have provided a partial solution, ideally the url will work with the latest ide version, but you said it as experimental so i think you will be working towards making it work with the latest version for everyone. I will try he board manager url with 1.6.4 and look forward to experimenting more with my rephone kits

**Comment by koko-ng** [comment]
I won't close my issue now because the source code isn't available. You sell the rephone as an open-souce product, but only the hardware is. Nowhere it's written that only the hardware is open source. Please upload the firmware and the upload tools source code.

Thanks for your responses.

**Comment by jamieisboss** [comment]
Having had some time to experiment with this a bit more, there is no way to update the firmware at all unless you're running windows. There aren't even closed binaries to download, I'm in agreement that the code should be released but even if you disagree with that, a least compile some mac and linux versions binaries so everyone is able to keep he devices up to date or it's impossible to continue to use the product. I can't mount the device into mass storage mode or as a COM port under ubuntu 15.10, which i can only guess either means i need a driver (which isn't available) or  firmware upgrade (which isn't possible) so im not able to use the Arduino IDE, LUA, Javascript or Eclipse, which only an old windows version of is supported. Essentially the [getting started guides on the wiki](http://www.seeedstudio.com/wiki/Arduino_IDE_for_RePhone_Kit) are **_all_** impossible to complete on a non windows pc. 

I was a kickstarter backer and it never said that the product was only compatible with microsoft windows, the [product page for the gsm+ble module](http://www.seeedstudio.com/depot/Xadow-GSM-BLE-p-2560.html) does not say that the module is only compatable with microsot windows. It is advertised as open source which is misleading if you will only release _some_ of the source code. 

Not even releasing drivers and firmware updaters for mac and Unix/Linux operating systems _without telling people_ when you are **selling** them the hardware means that i have spent money  on a **completely unusable** product that i cannot return. 

I have tried to be very helpful with the arduino IDE issues so I hope you can appreciate that it is very frustrating that I cannot develop anything at all using the 3x GSM+BLE,  1 x Rephone Create and 1x Rephone "All the Modules" kits that i have purchased. I have been excited to develop this type of device for some time and if i had [spent my money with another company](https://www.adafruit.com/products/1946) i would have been able to develop my solution, even [integrate the hardware design into my own product because it is open source](https://github.com/adafruit/Adafruit-FONA-800-GSM-Breakout) so long as i followed the conditions of the license. As it stands I have just wasted time waiting and it does not seem as though Seeed or mediatek are interested in making this hardware compatible with linux or mac.

Are here any plans at all to make it so that anyone using any common operating system can develop hardware using this platform? could you_ at least update the descriptions on the Seeed website to let people know that they require microsoft windows _to be able to develop using the Rephone system so that other people are not left in the same situation.

My only options are to go and spend an additional £80 on a windows license and run a virtual machine, or spend even more money and buy an additional device which runs windows, but not windows 10 because that isnt supported either! 

Please consider this and either update your website to tell people that you will not support development on any other platforms or provide the tools required to develop on them. Then if you do not wish to release the source code for your products, just stop calling it open source, because it is not. People will buy a product that is closed source with a good developer API as they have done for years so why not just be honest about what you are willing to give away the source for, nobody cares when companies do not release all of the code or designs for development platforms so long as they do not claim that they are open source products.

**Comment by durvesh09** [comment]
Hi,
   @WayenWeng , how to use sleep mode or power down mode in Rephone using your libraries ?
Please add example for sleep and wakeup of Xadow rephone ..

**Comment by durvesh09** [comment]
Hi,

 I recently bought 3 xadow rephone modules from Seeedstudio. I want to make use of PowerDown modes in rephone module but unable to get reference api for the same. Please provide assistance regarding using sleep modes/power down modes.

**Comment by durvesh09** [comment]
Hi,

  Is there any other way to Power down Xadow ?
Because there are API's written in Lua by LoBo (Github) for sleep mode and wake ups.
Also there is a timer called non-precise timers defined for waking up device , how can that timers be implemented to do the same ?
